OPT_LIGHT = 255 # Target light value out of 255
MAX_CHANGE = 25 # Largest change in brightness that happens over a second
BRIDGE_IP = "192.168.1.7" # Philips Hue IP address
OPT_TEMP = 25  # Target temp in C (unused)
LIGHT_NODE = 0 # Should be a list of nodes that are hue lights
UDP_IP = "192.168.1.100" # IP of the EnerGyan server
UPD_PORT = 5005 # Port of the EnerGyan serverr
CRIT_NODE = [3] # List of critical nodes not to touch
NUM_CLUSTERS = 2 # Number of sensor inputs to average
POWER_THRESHOLD_inRoom = 100 # Power threshold when someone is in the room
POWER_THRESHOLD_outRoom = 50 # Power threshold when no one is in the room
